config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "radar",     to: "participations#radar"
  get "dashboard", to: "pages#dashboard"
  get "events/current", to: "events#current", as: :current_event

  get "challenges/:id/rewards", to: "rewards#show", as: :reward
  get "challenges/:id/rewards/qrcode", to: "rewards#qrcode"
  get "challenges/:id/rewards/scan", to: "rewards#scan", as: :scan

  resources :participations, only: %i[update]

  resources :events do
    resources :participations, only: %i[new create]
    resources :relationships, only: %i[new create]
  end

  resources :participations, only: %i[show index] do
    resources :relationships, only: %i[new create]
  end

  resources :challenges, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :challenges, only: :show do
    resources :messages, only: :create
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :event
  has_one_attached :photo
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def show
    @challenge = Challenge.find(params[:id])
    @reward = @challenge.reward
  end

  def qrcode
    @challenge = Challenge.find(params[:id])
    @target_id = params[:target_id].to_i
    @user = current_user.id
    @sender = Participation.find(@challenge.relationship.sender_id).user_id
    @receiver = Participation.find(@challenge.relationship.receiver_id).user_id
    if @user == @sender
      @challenge.won! if @target_id == @receiver
      @test = 1
      redirect_to reward_path, status: :see_other
    elsif @user == @receiver
      @challenge.won! if @target_id == @sender
      @test = 2
      redirect_to reward_path, status: :see_other
    end
  end

  def scan
    @challenge = Challenge.find(params[:id])
  end

end

app/views/rewards/_qrcodesvg.html.erb
  <div class="d-flex flex-column align-items-center justify-content-center" style="width: 100%; margin-top: 35%">
    <div class="" style="width: 80%;background-color: white;padding: 20px">
      <% qrcode = RQRCode::QRCode.new("#{root_url}#{challenge_path[1..-1]}/rewards/qrcode?target_id=#{current_user.id}")
      # NOTE: showing with default options specified explicitly
      svg = qrcode.as_svg(
        color: "000000",
        shape_rendering: "crispEdges",
        module_size: 11,
        standalone: true,
        use_path: true,
        viewbox: true,
      )
      %>
      <%= svg.html_safe %>
    </div>
    <h4 class="mt-4 text-light">Your QRCODE</h4>
  </div>

app/views/rewards/_roulette.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<div class="contenedor">
  <div class="ruleta">
    <div class="colores">
      <div class="colorUno"></div>
      <div class="colorDos"></div>
      <div class="colorTres"></div>
      <div class="colorCuatro">Test</div>
    </div>
  </div>
</div>

<style id="animacion"></style>

<style>
  :root{
    --bg-cont-b: #303030;
    --bg-cont-b2: #515151;
    --bg-cont-w: #f5f5f5;
    --bg-b: #4285f4;
    --bg-r: #ea4335;
    --bg-y: #fbbc05;
    --bg-g: #34a853;
    --segundos: 1.2s;
  }


  html, body{
    height: 100vh;
    font-family: sans-serif;
    margin: 0;
  }

  html{
    font-size: 1.5vh;
  }

  body{
    background-color: var(--bg-cont-b);
    transition: background 0.2s;
    overflow: hidden;
  }

  .contenedor{
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .ruleta{
    width: 20rem;
    height: 20rem;
    position: relative;
    cursor: pointer;
    background-color: white;
    border-radius: 360rem;
  }

  .ruleta:before{
    content: "";
    width: 0;
    height: 0;
    border-left: 1rem solid transparent;
    border-right: 1rem solid transparent;
    border-top: 3rem solid white;
    position: absolute;
    top: 0.2rem;
    left: 50%;
    transform: translate(-50%);
    z-index: 999;
  }

  .ruleta:after{
    content: "";
    width: 1rem;
    height: 1rem;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    border-radius: 36rem;
    background-color: #fff;
    z-index: 999;
  }

  .colores{
    width: 20rem;
    height: 20rem;
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    flex-wrap: wrap;
    border-radius: 36rem;
    border: 1rem solid white;
    overflow: hidden;
    position: relative;
    justify-content: center;
    align-items: center;
    justify-items: center;
    align-content: center;
  }

  .animacion{
    animation: animacion 4s ease-out forwards;
    pointer-events: none;
  }

  .colorUno, .colorDos, .colorTres, .colorCuatro{
    width: 20rem;
    height: 20rem;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    font-size: 18px;
  }

  .colorUno{background-color: var(--bg-b);}
  .colorDos{background-color: var(--bg-r);}
  .colorTres{background-color: var(--bg-y);}
  .colorCuatro{background-color: var(--bg-g);}
</style>
<script>
  var multiplicador = 7;

  $('.ruleta').click(function(){
    $('body').css('background-color', 'var(--bg-cont-b');
    $('.ruleta').css('pointer-events', 'none');
    $('.colores').removeClass('animacion');
    var color = colorAleatorio(1, 360);

    $('#animacion').empty().append(
        '@keyframes animacion{'+
          '0%{transform: rotate(0deg)}'+
          '100%{transform: rotate('+color+'deg)}'+
        '}'
    );



    setTimeout(function(){
      $('.colores').addClass('animacion')
      //$('.colores').css('animation', 'animacion 4s ease-out forwards');
    },1)

    setTimeout(function(){
      if(color > 0 && color <= (90 + (360 * multiplicador))){
        $('body').css('background-color', 'var(--bg-b)')

      }else if(color > (90 + (360 * multiplicador)) && color <= (180 + (360 * multiplicador))){
        $('body').css('background-color', 'var(--bg-y)')

      }else if(color > (180 + (360 * multiplicador)) && color <= (270 + (360 * multiplicador))){
        $('body').css('background-color', 'var(--bg-g)')

      }else if(color > (270 + (360 * multiplicador))){
        $('body').css('background-color', 'var(--bg-r)')
      }

      $('.ruleta').css('pointer-events', 'initial');
    },4000);

  })

  function colorAleatorio(min, max) {
    var colorAleatorio = ((Math.random() * (max - min) + min).toFixed(0))*1;
    colorAleatorio = colorAleatorio + (360 * multiplicador);
    return colorAleatorio;
  }
</script>

app/views/rewards/qrcode.html.erb
<h1>test</h1>

app/views/rewards/scan.html.erb
<div class="d-flex flex-row justify-content-between align-items-center" style="width:88%;position: fixed; top: 20px; left: 16px;">
  <%= link_to challenge_path(@challenge), class: "pe-3" do %>
    <i class="fa-solid fa-chevron-left flashy"
      data-action="click->toggle-element#menuactive"
      data-toggle-element-target="menuactive"
      style="font-size:calc(1.275rem + 0.3vw)"></i>
  <% end %>
  <%= image_tag("logos/logo-em-flashy.png", :style => "width:120px; height:auto") %>
  <div></div>
</div>

<%# QRCODE READER %>
<div id="qr-reader" style="width: 100%; overflow: hidden; margin-top: 35%" data-controller="qrcode"></div>
<h4 class="text-light text-center mt-5">Scan your match QR Code</h4>

<%# Style to hide Camera Starting & Camera Stoping %>
<style>
  #html5-qrcode-button-camera-start {
    /* display: none !important; */
  }
  #html5-qrcode-button-camera-stop {
    display: none !important;
  }
  #qr-reader__dashboard_section {
    padding: 0px !important;
  }
</style>

<%# autoclick Permission %>
<%# <script>
// setTimeout(() => {
//   document.querySelector("#html5-qrcode-button-camera-permission").click()
// }, 500);
</script> %>

app/views/rewards/show.html.erb
<%# Return Arrow top of page %>
<div class="d-flex flex-row justify-content-between align-items-center" style="width:88%;position: fixed; top: 20px; left: 16px;">
  <%= link_to challenge_path(@challenge), class: "pe-3" do %>
    <i class="fa-solid fa-chevron-left flashy"
      data-action="click->toggle-element#menuactive"
      data-toggle-element-target="menuactive"
      style="font-size:calc(1.275rem + 0.3vw)"></i>
  <% end %>
  <%= image_tag("logos/logo-em-flashy.png", :style => "width:120px; height:auto") %>
  <div></div>
</div>

<%# IF Statement for reward show %>
<% if @challenge.status == "pending" %>
  <%= render 'rewards/challengepending', challenge: @challenge %>
  <%= render 'rewards/qrcodesvg', challenge: @challenge %>
<% elsif @challenge.status == "won" %>
  <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_GmaOBawqc8.json" background="transparent"  speed="0.7"  style="width: 100%; height: 60vh; position:absolute" loop autoplay></lottie-player>
  <div class="d-flex align-content justify-content-center align-items w-100">
    <div class="div-reward-win">
      <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_E3m1qQ.json" background="transparent"  speed="0.6"  style="width: 30%;" autoplay></lottie-player>
      <h1 class="text-light fw-bold"> <%= @reward.title %></h1>
      <h2 class="text-light"> <%= @reward.reward %></h2>
      <p class="text-light text-center mt-3">You can now claim your reward with your match - Congrats !</p>
      <div class="d-flex match">
        <%= cl_image_tag @challenge.relationship.sender.user.photos.first.key, width: 200, crop: :fill, class: "avatar-reward", style: 'z-index: 2' %>
        <%= cl_image_tag @challenge.relationship.receiver.user.photos.first.key, width: 200, crop: :fill, class: "avatar-reward", style: 'z-index: 2' %>
      </div>
    </div>
  </div>

  <%# <style>
    .div-reward-win {
      width: 70%;
      display: flex;
      flex-direction: column;
      align-content: center;
      justify-content: center;
      align-items: center;
      padding-top: 30%;
      background: #00000008;
      z-index: 2;
      position: relative;
      border-radius: 8px;
    }
  </style> %>

<% end %>