config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "radar",     to: "participations#radar"
  get "dashboard", to: "pages#dashboard"
  get "events/current", to: "events#current", as: :current_event

  get "challenges/:id/rewards", to: "rewards#show", as: :reward
  get "challenges/:id/rewards/qrcode", to: "rewards#qrcode"
  get "challenges/:id/rewards/scan", to: "rewards#scan", as: :scan

  resources :participations, only: %i[update]

  resources :events do
    resources :participations, only: %i[new create]
    resources :relationships, only: %i[new create]
  end

  resources :participations, only: %i[show index] do
    resources :relationships, only: %i[new create]
  end

  resources :challenges, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :challenges, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_fireworks.html.erb
<lottie-player src="https://assets7.lottiefiles.com/packages/lf20_GmaOBawqc8.json" background="transparent"  speed="0.7"  style="width: 100%; height: 80vh; position:absolute" loop autoplay></lottie-player>
<div class="d-flex align-content justify-content-center align-items w-100">
  <div class="div-reward-win">
    <h6 class="text-light">ID#<%= @reward.id %></h6>
    <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_E3m1qQ.json" background="transparent"  speed="0.6"  style="width: 30%;" autoplay></lottie-player>
    <h1 class="text-light"> <%= @reward.title %></h1>
    <h2 class="text-light"> <%= @reward.reward %></h2>
    <p class="text-light text-center mt-3">You go to one of our partner to claim your reward with your match - Congrats !</p>
  </div>
</div>

<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<style>
  .div-reward-win {
    width: 70%;
    display: flex;
    height: 100vh;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    align-items: center;
    padding-top: 30%;
    background: #00000008;
    z-index: 2;
    position: relative;
    border-radius: 8px;
  }
</style>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_info_window_html.erb
<div style="width: 200px;">
  <%= link_to event_path(event) ,class: "text-decoration-none" do %>
    <%= cl_image_tag event.photos.first.key, width: 1000, crop: :fill, class: "rounded", style:"height: 150px; width: 100%; object-fit: cover"%>
    <div class="align-items-start d-flex flex-column justify-content-start p-3 text-black">
      <h3><%= event.name %></h3>
      <p class="m-0">Address: <%= event.address %></p>
      <p class="m-0">Starts: <%= event.start_date %></p>
    </div>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_marker.html.erb
<%#= image_tag "icons/favicon.ico", height: 30, width: 30, alt: "Logo" %>
<%= cl_image_tag participation.user.photos.first.key, width: 50, crop: :fill, style:"height: 40px;
                                                                                        width: 40px;
                                                                                        object-fit: cover;
                                                                                        border-radius: 50%;",
                                                                                        class: "pulse" %>

app/views/shared/_menu.html.erb
<div class="px-3 border-0 text-white">
  <div data-controller="toggle-element">

    <% unless params[:controller] == "challenges" && params[:action] == "show" || params[:controller] == "rewards" %>

      <div class="d-flex navbar-menu justify-content-between">
        <div class="d-flex flex-column justify-content-center">
          <i class="fa fa-bars"
            data-action="click->toggle-element#menuactive"
            data-toggle-element-target="menuactive"
            style="font-size:calc(1.275rem + 0.3vw)"></i>
        </div>
        <%= image_tag("logos/logo-em-flashy.png", :style => "width:120px; height:auto") %>
        <div> </div>
      </div>


      <div class="event-channel" data-toggle-element-target="modal">
        <i
          class="fa-solid fa-chevron-left"
          data-action="click->toggle-element#menuactive"
          data-toggle-element-target="menuactive"
          style="font-size:calc(1.275rem + 0.3vw);
                  top: 0px;
                  position: fixed;
                  padding: 16px;
                  left: 0;"
        ></i>

        <%= link_to root_path do %>
          <% if params[:controller] == "pages" && params[:action] != "dashboard" || params[:controller] == "participations" && params[:action] == "index" %>
            <span class="menu-highlight-container"><span class="highlight">Home Page</span></span>
          <% else %>
            <span>Home Page</span>
          <% end %>
        <% end %>

        <%= link_to current_event_path do %>
          <% if params[:controller] == "events" || params[:controller] == "relationships" || params[:controller] == "challenges" %>
            <span class="menu-highlight-container"><span class="highlight">My Event</span>
          <% else %>
            <span>My Event</span>
          <% end %>
        <% end %>

        <%= link_to dashboard_path do %>
          <% if params[:action] == "dashboard" %>
            <span class="menu-highlight-container"><span class="highlight">My Profile</span>
          <% else %>
            <span>My Profile</span>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_menu_messages.html.erb
<div class="message-menu">

  <div class="message-menu-first d-flex align-items-center text-white justify-content-between w-100">

    <div class="d-flex align-items-center">
      <%= link_to challenges_path, class: "pe-3" do %>
        <i class="fa-solid fa-chevron-left flashy"
          data-action="click->toggle-element#menuactive"
          data-toggle-element-target="menuactive"
          style="font-size:calc(1.275rem + 0.3vw)"></i>
      <% end %>
      <div class="d-flex flex-column">
        <p class="message-menu-target"><%= target.user.first_name.capitalize %></p>
      </div>
    </div>

    <div>
    </div>
  </div>

  <div class="message-submenu">
    <div class="message-menu-photo">
      <%= cl_image_tag target.user.photos.first.key, width: 1000, crop: :fill %>
    </div>
    <div>
      <div class="message-submenu-info">
        <h3><%= target.hint.upcase %></h3>
        <% if challenge.pending? %>
          <p>Did you find <%= target.user.first_name %> ?</p>
        <% elsif challenge.won? %>
          <p>Well done, you found <%= target.user.first_name %></p>
        <% else %>
          <p>Challenge finished</p>
        <% end %>
      </div>
      <div class="d-flex">
        <%= link_to reward_path do %>
          <button class="message-submenu-button">
            <i class="fa-solid fa-qrcode px-2"></i>
            <p class="pe-2">QR-Code</p>
          </button>
        <% end %>
        <%= link_to scan_path do %>
          <button class="message-submenu-button">
            <i class="fa-solid fa-camera px-2"></i>
            <p class="pe-2">Scan</p>
          </button>
        <% end %>
        <%= link_to reward_path do %>
          <button class="message-submenu-button">
            <i class="fa-solid fa-gift px-2"></i>
            <p class="pe-2">Reward</p>
          </button>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_modal.html.erb
<div id="astro-modal" class="hidden">
  <div class="astro-modal-backdrop">
    <span class="close-button">
      <i class="fa-solid fa-xmark"></i>
    </span>
    <div class="astro-modal-body no-scrollbar">
      <div class="astro-modal-content">
        <!-- LOADER (genre spinner) -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if params[:controller] == "pages" && params[:action] != "dashboard" || params[:controller] == "participations" %>

  <nav class="navbar navbar-light justify-content-between " data-controller="navbar">
    <div class="nav-item active">
      <%= link_to root_path, class: "nav-link",
                            "data-navbar-target": "home" do %>
        <% if params[:action] == "home" %>
          <i class="fa-solid fa-house flashy"></i>
        <% else %>
          <i class="fa-solid fa-house"></i>
        <% end %>
      <% end %>

      <%= link_to participations_path, class: "nav-link",
                            "data-navbar-target": "home" do %>
        <% if params[:controller] == "participations" && params[:action] == "index" %>
          <i class="fa-regular fa-calendar-check flashy"></i>
        <% else %>
          <i class="fa-regular fa-calendar-check"></i>
        <% end %>
      <% end %>
    </div>
  </nav>

<%
  elsif params[:controller] == "events" ||
        params[:controller] == "relationships" ||
        params[:controller] == "challenges" && params[:action] != "show"
%>
  <nav class="navbar navbar-light justify-content-between " data-controller="navbar">

    <div class="nav-item active">
      <%= link_to current_event_path, class: "nav-link" do %>
        <% if params[:controller] == "events" %>
          <i class="fa-solid fa-play flashy"></i>
        <% else %>
          <i class="fa-solid fa-play"></i>
        <% end %>
      <% end %>

      <% if current_user.nil? || current_user.current_event.nil? %>
        <span class="nav-link">
          <% if params[:controller] == "relationships" %>
            <i class="fa-solid fa-heart flashy"></i>
          <% else %>
            <i class="fa-solid fa-heart"></i>
          <% end %>
        </span>
      <% else %>
        <%= link_to new_participation_relationship_path(current_user.current_participation), class: "nav-link" do %>
          <% if params[:controller] == "relationships" %>
            <i class="fa-solid fa-heart flashy"></i>
          <% else %>
            <i class="fa-solid fa-heart"></i>
          <% end %>
        <% end %>
      <% end %>

      <%= link_to challenges_path, class: "nav-link" do %>
        <% if params[:controller] == "challenges" && params[:action] != "show" %>
          <i class="fa-solid fa-comments flashy"></i>
        <% else %>
          <i class="fa-solid fa-comments"></i>
        <% end %>
      <% end %>
    </div>
  </nav>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_with url: root_path, method: :get, class: "d-flex justify-content-between search-form" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "search-bar",
    placeholder: "Find an event",
    autocomplete: "off"
  %>

    <%#= text_field_tag :geo,
    params[:geo],
    class: "search-bar",
    placeholder: "Search an event by address",
    autocomplete: "off"
  %>

  <%= button_tag type: 'submit', class: "search-button" do %>
    <i class="fa-solid fa-magnifying-glass fs-4"></i>
  <% end %>
<% end %>

app/views/shared/_swiper.html.erb
<div class="swiper" data-controller="swipe coordinates modal">
  <div class="swiper__content">
    <div class="swiper__card-cont"
         data-swipe-target="content"
         data-participation-id="<%= @current_participation.id %>">
      <% participations.each do |participation| %>
          <div class="swiper__card"
              data-swipe-target="card"
              data-id="<%= participation.id %>">
            <span class="profile-link hidden" data-action="click->modal#open" data-modal-url-param="<%= participation_path(participation)%>"></span>
            <div class="swiper__card__content">

            <div class="swiper__card__content_top">
              <%# La partie du haut de la carte %>
            </div>

            <% if participation.user.photos.attached? %>
              <%= cl_image_tag participation.user.photos.first.key, class: 'swiper__card__img', alt:"Picture" %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1454908027598-28c44b1716c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" class="swiper__card__img" alt="...">
            <% end %>

            <div class="swiper__card__content_bottom">
              <p class="swiper__card__name">
                <strong><%= participation.user.first_name %></strong>, <span class="profile-age"><%= participation.user.age %></span>
              </p>
            </div>
            </div>
            <div class="swiper__card__choice m--reject"></div>
            <div class="swiper__card__choice m--like"></div>
            <div class="swiper__card__drag"></div>
          </div>
      <% end %>
    </div>
  </div>