config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "radar",     to: "participations#radar"
  get "dashboard", to: "pages#dashboard"
  get "events/current", to: "events#current", as: :current_event

  get "challenges/:id/rewards", to: "rewards#show", as: :reward
  get "challenges/:id/rewards/qrcode", to: "rewards#qrcode"
  get "challenges/:id/rewards/scan", to: "rewards#scan", as: :scan

  resources :participations, only: %i[update]

  resources :events do
    resources :participations, only: %i[new create]
    resources :relationships, only: %i[new create]
  end

  resources :participations, only: %i[show index] do
    resources :relationships, only: %i[new create]
  end

  resources :challenges, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :challenges, only: :show do
    resources :messages, only: :create
  end
end

app/views/pages/_event_card.html.erb
<% @events.each do | event | %>
  <div class="event-card-wrapper" data-controller="toggle-element">
    <div class="event-card" data-action="click->toggle-element#toggle">
      <div class="event-image">
        <%= cl_image_tag event.photos.first.key, width: 1000, crop: :fill %>
      </div>
      <h3><%= event.title %></h3>
      <div class="event-description">
        <p> <%= event.description.size > 100 ? "#{event.description.first(110)} ..." : event.description %> </p>
      </div>
    </div>

    <div class="event-modal" data-toggle-element-target="modal">
      <div class="wrapper-relative">
        <div class="event-image">
          <%= cl_image_tag event.photos.first.key, width: 1000, crop: :fill %>
        </div>

        <div class="container">
          <div class="gen-infos">
            <p>When? From <%= event.start_date.strftime("%A %B %e") %> to <%= event.end_date.strftime("%A %B %e") %></p>
            <p>Where? <%= event.address %></p>
            <h1><%= event.title %></h1>
              <div class="dev">
                <p><%= event.description %></p>
              </div>

              <% if user_signed_in? %>
              <div class="container" >
                <%= simple_form_for [event, @participation] do |f| %>
                  <%= f.input :event_id, as: :hidden, input_html: { value: event.id } %>
                  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
                  <%= f.input :hint ,placeholder: "Mon indice"%>
                  <%= f.submit class: 'btn btn-primary text-white p-2 w-100' %>
                <% end %>
              </div>
              <% end %>
          </div>
          <i class="fa-solid fa-x" data-action="click->toggle-element#toggle"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/_event_modal.html.erb
<div class="event-modal" data-toggle-element-target="modal">
  <div class="wrapper-relative">
    <div class="container-event">
      <div class="mb-3">
        <% if event.photos.attached? %>
          <%= cl_image_tag event.photos.first.key, width: 1000, crop: :fill , class:"event-img" %>
        <% else %>
          <%= image_tag "https://cdn.sortiraparis.com/images/61/1665/838944-solidays-2023-a-paris-ouverture-de-la-billetterie-debut-fevrier.jpg", class:"event-img-modal", style:"height: 40vh; width: 100%" %>
        <% end %>

      </div>
      <i class="fa-solid fa-chevron-left back" data-action="click->toggle-element#toggle"></i>
      <div class="overlay-image"></div>
    </div>

    <div>
      <h1 class="text-white font-weight-bold px-3"><%= event.title %></h1>
      <div class="d-flex flex-row align-items-center mt-3 px-3">
        <i class="fa-solid fa-calendar-days me-2 white" style=""></i>
        <p class="paragraph-event me-1"><%= event.start_date.strftime("%D") %> -</p>
        <p class="paragraph-event"><%= event.end_date.strftime("%D") %></p>
      </div>
      <div class="d-flex flex-row align-items-center mt-2 px-3">
        <i class="fa-solid fa-location-dot me-2 white" style="width:10px;"></i>
        <p class="paragraph-event"> <%= event.address %> </p>
      </div>
      <div class="mt-4 px-3">
        <%= render "events/participations", participations: event.participations %>
      </div>
      <div class="mt-4">
        <h3 class="text-white mt-4 mb-0 px-3">Rewards</h3>
        <%= render "events/rewards", rewards: event.rewards %>
      </div>
      <h3 class="text-white mt-4 px-3">Infos</h3>
      <p class="paragraph-event mt-2 px-3" style="padding-bottom: 140px"><%= event.description %></p>
    </div>
    <% if user_signed_in? %>
      <div class="div-join-button" data-controller="modal">
        <button class="join-button btn profile-link d-none" data-toggle-element-target="button" data-action="click->modal#open" data-modal-url-param="<%= new_event_participation_path(event)%>">Join</button>
      </div>
    <% else %>
      <div class="div-join-button">
        <button class="join-button btn btn-primary d-none" data-toggle-element-target="button"%>
        <a href="users/sign_in" style="color:inherit"> Log in </a></button>
      </div>
    <% end %>
    <%# <div class="form-bottom">
      <%= render "pages/participation_submit", event: event, participation: @participation %>
    <%# </div> %>
  </div>
</div>

app/views/pages/_participation_submit.html.erb
<div class="container border-0">
  <div class="d-flex flex-row align-content-center justify-content-center align-items-center text-white">
      <%= simple_form_for [event, participation],html: { class: "w-100"} do |f| %>
        <%= f.input :event_id, as: :hidden, input_html: { value: event.id } %>
        <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.input :hint, label: :"Give a hint to find you easily", placeholder: "Your hint"%>
        <%= f.submit "Confirm", class: 'btn text-white p-2 w-100 mt-1 join-button' %>
      <% end %>
  </div>
</div>

app/views/pages/_profile_modal.html.erb
<div class="profile-modal" data-profile-target="modal">
  <div class="wrapper-relative">
    <div class="container-profile">
      <div class="mb-3">
        <% if participation.user.photos.attached? %>
          <%= cl_image_tag participation.user.photos.first.key, width: 1000, crop: :fill, class:"profile-img" %>
        <% else %>
          <%= image_tag "https://cdn.sortiraparis.com/images/61/1665/838944-solidays-2023-a-paris-ouverture-de-la-billetterie-debut-fevrier.jpg", class:"event-img", style:"height: 40vh" %>
        <% end %>
      <h1 class="text-white font-weight-bold"><%= participation.user.first_name %></h1>
      <p>Vit ici :<%= participation.user.city %>  </p>
      <h2>A propos de moi</h2>
      <p><%= participation.user.description %>  </p>
      <h2>Passions</h2>
      <%# participation.user.tags.to_a each do |tag| %>
      <%# end %>
      <h2>Mes événements</h2>
      </div>
      <i class="fa-solid fa-chevron-left back" data-action="click->profile#toggle"></i>
      <div class="overlay-image"></div>
    </div>
  </div>
</div>

app/views/pages/_scroll_events.html.erb
<h3 class="section-title px-3 mt-4">
  <span class="highlight-container"><span class="highlight"><%= category %></span></span>
</h3>
<div class="scrollmenu mt-1 px-3">
  <% events.each do |event| %>
    <div class="me-2 pb-3 scrollsubmenu" data-controller="toggle-element">
        <%= cl_image_tag event.photos.first.key, width: 1000, crop: :fill, class: 'scroll-event-card', data: { action: "click->toggle-element#toggle" } %>
        <h5 class="scroll-event-title"><%= event.title.capitalize %></h5>
        <span class="scroll-event-dates"><%= event.start_date.strftime("%D") %> - <%= event.end_date.strftime("%D") %></span>
        <%#= render "event_modal", event: event %>
       <%#= render "pages/event_modal",  event: event %>
    </div>
  <% end %>
</div>

app/views/pages/_top_event.html.erb
<h3 class="section-title px-3">
  <span class="highlight-container"><span class="highlight">Top 10</span></span>
</h3>
<div class="scrollmenu px-3">
  <% events.each_with_index do |event, index| %>
      <div class="me-2 pb-3 top-scrollsubmenu" data-controller="toggle-element">
        <div class="position-relative">
          <%= cl_image_tag event.photos.first.key, width: 1000, crop: :fill, class: 'top-event-card', data: { action: "click->toggle-element#toggle" } %>
          <p class="top-numbers"><%= index + 1 %></p>
        </div>
        <%#= render "event_modal", event: event %>
        <%= render "pages/event_modal",  event: event %>

      </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container text-white">
  <div class="d-flex align-items-center justify-content-between mt-2 mb-2">
    <div class="dashboard-title mt-2 mb-3 w-100">
      <h4>My Personal Data</h4>
      <div class="d-flex justify-content-between">
        <div class="top-infos">
          <p>Name: <%= "#{current_user.first_name} #{current_user.last_name}" %></p>
          <p>E-mail: <%= current_user.email %></p>
          <p>City: <%= current_user.city %></p>
        </div>
        <%= cl_image_tag current_user.photos.first.key, width: 1000, crop: :fill, class: "avatar-3" %>
      </div>
    </div>
  </div>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary", form_class: "button_to d-flex justify-content-center"%>
</div>

app/views/pages/home.html.erb
<!--
<div class="sticky-top title">
  <h4 class="m-0">Even meet</h4>
</div>
-->

<div class="">
  <div class="search mb-3 px-3">
    <%= render "shared/search_form" %>
  </div>
  <%= render 'top_event',     events: @events.first(10) %>
  <%= render 'scroll_events', events: @events.shuffle, category: "Rock"%>
  <%= render 'scroll_events', events: @events.shuffle, category: "Techno"%>
  <%= render 'scroll_events', events: @events.shuffle, category: "Rap"%>
  <%= render 'scroll_events', events: @events.shuffle, category: "Psy-Trans"%>
</div>